### ISSUE TITLE
Server thinks this mod is client-required and will be marked with a big red X saying "FML Incompatible Forge Modded Server"

### ISSUE THREAD

**Issue by Minoxs** [Commoble/cant-sleep-clowns-will-eat-me#1]
This is very easy to fix, just add:
```java
ModLoadingContext.get().registerExtensionPoint(ExtensionPoint.DISPLAYTEST, () -> Pair.of(() -> FMLNetworkConstants.IGNORESERVERONLY, (a, b) -> true));
```
to your main class ( CantSleepClownsWillEatMe() ).
Source: https://mcforge.readthedocs.io/en/latest/concepts/sides/

p.s: Tested this change on my server and it worked :)

**Comment by Commoble** [comment]
Thank you, this should have a fix up soon
